FROM postgres

USER postgres
WORKDIR /app

COPY src/main/kotlin/SQL/create.sql /docker-entrypoint-initdb.d/1_create.sql
COPY src/main/kotlin/SQL/initial.sql /docker-entrypoint-initdb.d/2_insert-test-data.sql

COPY --chown=postgres:postgres ./tests/scripts/wait-for-postgres.sh ./bin/wait-for-postgres.sh
RUN chmod +x ./bin/wait-for-postgres.sh

EXPOSE 5432